name: my_quiz
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2 
  firebase_auth: ^4.15.3
  # Database NoSQL dari Firebase (Firestore).
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.6.9
  firebase_analytics: ^10.9.5
  firebase_messaging: ^14.8.7
  intl: ^0.18.1
  # Plugin untuk login dengan akun Google.
  google_sign_in: ^6.1.6 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/sounds/
  #   - assets/fonts/ 