// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2BM_QXzeqen7kpuD-z2jZo6kzmua2qV4',
    appId: '1:853888644110:web:043113dc28e092d451785f',
    messagingSenderId: '853888644110',
    projectId: 'myquiz-4769a',
    authDomain: 'myquiz-4769a.firebaseapp.com',
    storageBucket: 'myquiz-4769a.firebasestorage.app',
    measurementId: 'G-YY2ZZQVWH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNRm0p3-8dxYs00UxY5LbDyHfiwHQ7dfg',
    appId: '1:853888644110:android:aa7bb63f20a6add351785f',
    messagingSenderId: '853888644110',
    projectId: 'myquiz-4769a',
    storageBucket: 'myquiz-4769a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClmrCKvmHQNpWoccKPTd2affySlqVrLl8',
    appId: '1:853888644110:ios:12ca586a2ae6c9fd51785f',
    messagingSenderId: '853888644110',
    projectId: 'myquiz-4769a',
    storageBucket: 'myquiz-4769a.firebasestorage.app',
    iosBundleId: 'com.example.myQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClmrCKvmHQNpWoccKPTd2affySlqVrLl8',
    appId: '1:853888644110:ios:12ca586a2ae6c9fd51785f',
    messagingSenderId: '853888644110',
    projectId: 'myquiz-4769a',
    storageBucket: 'myquiz-4769a.firebasestorage.app',
    iosBundleId: 'com.example.myQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2BM_QXzeqen7kpuD-z2jZo6kzmua2qV4',
    appId: '1:853888644110:web:42c85933ceb2124a51785f',
    messagingSenderId: '853888644110',
    projectId: 'myquiz-4769a',
    authDomain: 'myquiz-4769a.firebaseapp.com',
    storageBucket: 'myquiz-4769a.firebasestorage.app',
    measurementId: 'G-5YM61182V8',
  );
}
